#ifndef GLOBALS_H
#define GLOBALS_H

enum STATE{LOADING, LOGIN, CHECKINGLOGIN, MENU, ABOUT, LOADSERVERLIST, SERVERLIST, CONNECTINIT, CONNECTING, GAME, DISCONNECT, CLOSE};

const int ScreenHeight = 600;
const int ScreenWidth = 800;

#endif // GLOBALS_H
